[tasks.run]
usage = '''
arg "[args]..."
'''

run = 'go run main.go {{ arg(name="args") }}'

[tasks.build]
usage = '''
arg "<os>"
arg "<arch>"
arg "[args]..."
'''

run = '''
#!/usr/bin/env bash
set -eu

os={{ arg(name="os") }}
arch={{ arg(name="arch") }}
out=build/${os}_${arch}
args={{ arg(name="args") }}

if [ $os = "windows" ]; then
    out+=".exe"
fi

GOOS=$os GOARCH=$arch go build -o $out $args
'''

run_windows = '''
#!powershell.exe
$ErrorActionPreference = "Stop"

os = {{ arg(name="os") }}
arch = {{ arg(name="arch") }}
out = build/${os}_${arch}
args = {{ arg(name="args") }}

if ($os -eq "windows") {
    $out += ".exe"
}

$env:GOOS=$os; $env:GOARCH=$arch; go build -o $out $args
'''

[tasks.crossbuild]
depends = [
    "build linux amd64",
    "build linux 386",
    "build darwin amd64",
    "build darwin arm64",
    "build windows amd64",
    "build windows 386",
]
