[tasks.activate]
run = '''
#!/usr/bin/env bash
bash --login -c '
    eval "$(mise activate bash)"
    exec bash
'
'''

run_windows = '''
#!powershell.exe
$env:MISE_PWSH_CHPWD_WARNING=0
powershell.exe -Command "
    mise activate pwsh |
        Out-String |
        Invoke-Expression
    powershell.exe `
        -NoLogo `
        -NoProfile
"
'''

[tasks.run]
usage = '''
arg "[args]..."
'''

run = 'go run main.go $usage_args'

[tasks.build]
usage = '''
arg "<os>"
arg "<arch>"
arg "[args]..."
'''

run = '''
#!/usr/bin/env bash
set -eu
out=build/${usage_os}_${usage_arch}
if [ $usage_os = "windows" ]; then
    out+=".exe"
fi
export GOOS=$usage_os
export GOARCH=$usage_arch
go build -o $out ${usage_args:-}
'''

run_windows = '''
#!powershell.exe
$ErrorActionPreference = "Stop"
$out = "build/${usage_os}_${usage_arch}"
if ($usage_os -eq "windows") {
    $out += ".exe"
}
$env:GOOS=$usage_os
$env:GOARCH=$usage_arch
go build -o $out $usage_args
'''

[tasks.crossbuild]
depends = [
  "build linux amd64",
  "build linux 386",
  "build darwin amd64",
  "build darwin arm64",
  "build windows amd64",
  "build windows 386",
]
