[tools]
"aqua:nushell/nushell" = "0.115.0"
go = "1.26.0"
"go:golang.org/x/tools/gopls" = "0.23.0"

[settings]
quiet = true

[task_config]
shell = "nu -c"

[tasks.exec]
description = "run the application"
usage = 'arg "[args]..." default=""'
run = 'go run . -- $env.usage_args'

[tasks.vet]
description = "run static analysis"
run = 'go vet ./...'

[tasks.fmtcheck]
description = "check code formatting"
run = 'gofmt -l .'

[tasks.fmt]
description = "format all files"
run = 'go fmt ./...'

[tasks.test]
description = "run tests"
run = 'go test -failfast -count 1 ./...'

[tasks.build]
description = "build for a specific platform"

usage = '''
arg <os> help="target operating system"
arg <arch> help="target architecture"
'''

run = '''
$env.GOOS = $env.usage_os
$env.GOARCH = $env.usage_arch
mut out = $"build/($env.GOOS)_($env.GOARCH)"
if $env.GOOS == "windows" {
    $out += ".exe"
}
go build -ldflags "-s -w" -o $out
'''

[tasks.crossbuild]
description = "build for all supported platforms"

depends = [
  "build linux amd64",
  "build linux 386",
  "build darwin amd64",
  "build darwin arm64",
  "build windows amd64",
  "build windows 386",
]
