name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: pkgxdev/setup@v5

      - run: pkgx just crossbuild
