name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

jobs:
  main:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: pkgxdev/setup@v5

      - run: pkgx just crossbuild

      - run: gh release create "v4.0.0" build/* --title "v4.0.0" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
